packages:
  - 'apps/*'
  - 'packages/*'

# Pacotes nativos que precisam rodar scripts de build (bindings, engines)
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: false
